Add integration with backend and simpleModal hook [IO-135]
PW-MiNI-IO2-2022-Group-1/grupa-o-aabs-frontend pull request #19
Opened 2022-04-13 20:20 UTC by adamczykt

2022-04-14 19:42 UTC, V1OL3TF0X requested changes

2022-04-14 19:42 UTC, V1OL3TF0X commented on src/components/VaccineChoiceForm.tsx
> +                showModal('Error', 'Unexpected error');
Podoba mi się ten pomysł

2022-04-14 19:42 UTC, V1OL3TF0X commented on src/logic/patientApi.ts
> +                "Authorization": auth.token ?? ""
zmień na '' pls, consistency

2022-04-16 10:44 UTC, adamczykt commented on src/logic/patientApi.ts
> +                "Authorization": auth.token ?? ""
Done

2022-04-16 10:44 UTC, merged